// AUTO-GENERATED BY SFXTypeGenerator. DO NOT EDIT.
// Regenerate with Tools > Audio > Regenerate SFXType.
// The first 1 member(s) are reserved and have no clip; after them,
// member order matches the line order of Assets/Resources/AudioClipFilePaths.txt.

public enum SFXType
{
    NoSFX, // reserved: no audio clip
    CampBattle1, // Audio/Music/Battle/Camp Battle1
    CampBattle2, // Audio/Music/Battle/Camp Battle2
    CampBattle3, // Audio/Music/Battle/Camp Battle3
    CampBattle, // Audio/Music/Camp Battle
    CampInterior, // Audio/Music/Camp Interior
    CampOverworld, // Audio/Music/Camp Overworld
    Cave1, // Audio/Music/Cave 1
    Cave2, // Audio/Music/Cave 2
    Dead, // Audio/Music/Dead
    CampInteriorOld, // Audio/Music/Old Music/Camp Interior (Old)
    Win, // Audio/Music/Win
    Birds, // Audio/Sound Effects/Ambience/Birds
    Crowd, // Audio/Sound Effects/Ambience/Crowd
    BatAttack, // Audio/Sound Effects/Attack Sounds/Bats/Bat Attack
    BatHowl, // Audio/Sound Effects/Attack Sounds/Bats/Bat Howl
    Bats_BatSwarm, // Audio/Sound Effects/Attack Sounds/Bats/Bat Swarm
    HorseWhinny, // Audio/Sound Effects/Attack Sounds/Horse/Horse Whinny
    Bite, // Audio/Sound Effects/Attack Sounds/Misc/Bite
    PlacePartyMember, // Audio/Sound Effects/Attack Sounds/Misc/PlacePartyMember
    Smokebomb, // Audio/Sound Effects/Attack Sounds/Misc/Smokebomb
    WeaponSwing, // Audio/Sound Effects/Attack Sounds/Weapons/WeaponSwing
    Whip, // Audio/Sound Effects/Attack Sounds/Weapons/Whip
    WormAcidVomit, // Audio/Sound Effects/Attack Sounds/Worms/WormAcidVomit
    WormExplodeOnDeath, // Audio/Sound Effects/Attack Sounds/Worms/WormExplodeOnDeath
    WormSummon, // Audio/Sound Effects/Attack Sounds/Worms/WormSummon
    OnTransition, // Audio/Sound Effects/BetweenAreas/OnTransition
    Coin1, // Audio/Sound Effects/Coin/Coin1
    Coin2, // Audio/Sound Effects/Coin/Coin2
    Coin3, // Audio/Sound Effects/Coin/Coin3
    Coin4, // Audio/Sound Effects/Coin/Coin4
    Coin5, // Audio/Sound Effects/Coin/Coin5
    BatDeath1, // Audio/Sound Effects/Death Sounds/Bats/Bat Death 1
    BatDeath2, // Audio/Sound Effects/Death Sounds/Bats/Bat Death 2
    FemaleHuman_Death, // Audio/Sound Effects/Death Sounds/Female Human/Death
    Horse_Death, // Audio/Sound Effects/Death Sounds/Horse/Death
    MaleHuman_Death, // Audio/Sound Effects/Death Sounds/Male Human/Death
    FemaleHuman_Intro1, // Audio/Sound Effects/Dialogue/Female Human/Intro1
    FemaleHuman_Intro2, // Audio/Sound Effects/Dialogue/Female Human/Intro2
    FemaleHuman_Intro3, // Audio/Sound Effects/Dialogue/Female Human/Intro3
    HorseIntro, // Audio/Sound Effects/Dialogue/Horse/HorseIntro
    MaleHuman_Intro1, // Audio/Sound Effects/Dialogue/Male Human/Intro1
    MaleHuman_Intro2, // Audio/Sound Effects/Dialogue/Male Human/Intro2
    MaleHuman_Intro3, // Audio/Sound Effects/Dialogue/Male Human/Intro3
    CrateIntro, // Audio/Sound Effects/Dialogue/Objects/CrateIntro
    GateIntro, // Audio/Sound Effects/Dialogue/Objects/GateIntro
    RockIntro, // Audio/Sound Effects/Dialogue/Objects/RockIntro
    Snoring, // Audio/Sound Effects/Dialogue/Sleeping/Snoring
    ActionEquip, // Audio/Sound Effects/EquipUnequip/Actions/ActionEquip
    ActionUnequip, // Audio/Sound Effects/EquipUnequip/Actions/ActionUnequip
    Body, // Audio/Sound Effects/EquipUnequip/Armor/Body
    Feet, // Audio/Sound Effects/EquipUnequip/Armor/Feet
    Hands, // Audio/Sound Effects/EquipUnequip/Armor/Hands
    Head, // Audio/Sound Effects/EquipUnequip/Armor/Head
    Shield, // Audio/Sound Effects/EquipUnequip/Armor/Shield
    Trinket, // Audio/Sound Effects/EquipUnequip/Armor/Trinket
    Weapon1, // Audio/Sound Effects/EquipUnequip/Weapon/Weapon1
    Weapon2, // Audio/Sound Effects/EquipUnequip/Weapon/Weapon2
    Weapon3, // Audio/Sound Effects/EquipUnequip/Weapon/Weapon3
    Cave_FS1, // Audio/Sound Effects/Footsteps/Cave/FS1
    Cave_FS2, // Audio/Sound Effects/Footsteps/Cave/FS2
    Cave_FS3, // Audio/Sound Effects/Footsteps/Cave/FS3
    Cave_FS4, // Audio/Sound Effects/Footsteps/Cave/FS4
    Cave_FS5, // Audio/Sound Effects/Footsteps/Cave/FS5
    Cave_FS6, // Audio/Sound Effects/Footsteps/Cave/FS6
    Cave_FS7, // Audio/Sound Effects/Footsteps/Cave/FS7
    FS8, // Audio/Sound Effects/Footsteps/Cave/FS8
    FS9, // Audio/Sound Effects/Footsteps/Cave/FS9
    Dirt_FS1, // Audio/Sound Effects/Footsteps/Dirt/FS1
    Dirt_FS2, // Audio/Sound Effects/Footsteps/Dirt/FS2
    Dirt_FS3, // Audio/Sound Effects/Footsteps/Dirt/FS3
    Dirt_FS4, // Audio/Sound Effects/Footsteps/Dirt/FS4
    Dirt_FS5, // Audio/Sound Effects/Footsteps/Dirt/FS5
    Dirt_FS6, // Audio/Sound Effects/Footsteps/Dirt/FS6
    Dirt_FS7, // Audio/Sound Effects/Footsteps/Dirt/FS7
    WoodFloor_FS1, // Audio/Sound Effects/Footsteps/WoodFloor/FS1
    WoodFloor_FS2, // Audio/Sound Effects/Footsteps/WoodFloor/FS2
    WoodFloor_FS3, // Audio/Sound Effects/Footsteps/WoodFloor/FS3
    WoodFloor_FS4, // Audio/Sound Effects/Footsteps/WoodFloor/FS4
    WoodFloor_FS5, // Audio/Sound Effects/Footsteps/WoodFloor/FS5
    Acid, // Audio/Sound Effects/Hit/Acid/Acid
    BatSwarm_BatSwarm, // Audio/Sound Effects/Hit/BatSwarm/BatSwarm
    Healing, // Audio/Sound Effects/Hit/Healing/Healing
    Negative, // Audio/Sound Effects/Hit/Negative/Negative
    Pierce, // Audio/Sound Effects/Hit/Pierce/Pierce
    Positive, // Audio/Sound Effects/Hit/Positive/Positive
    Slash, // Audio/Sound Effects/Hit/Slash/Slash
    Sip, // Audio/Sound Effects/Items/Drinking/Sip
    Eating1, // Audio/Sound Effects/Items/Eating/Eating1
    Eating2, // Audio/Sound Effects/Items/Eating/Eating2
    Eating3, // Audio/Sound Effects/Items/Eating/Eating3
    Eating4, // Audio/Sound Effects/Items/Eating/Eating4
    Eating5, // Audio/Sound Effects/Items/Eating/Eating5
    Eating6, // Audio/Sound Effects/Items/Eating/Eating6
    ButtonOff, // Audio/Sound Effects/Misc/ButtonOff
    ButtonOn, // Audio/Sound Effects/Misc/ButtonOn
    ChestOpen, // Audio/Sound Effects/Misc/ChestOpen
    Execution, // Audio/Sound Effects/Misc/Execution
    GateOpen, // Audio/Sound Effects/Misc/GateOpen
    GateOpenShort, // Audio/Sound Effects/Misc/GateOpenShort
    Gong, // Audio/Sound Effects/Misc/Gong
    JellyMisfire, // Audio/Sound Effects/Misc/JellyMisfire
    LvlUp, // Audio/Sound Effects/Misc/LvlUp
    PlaceInInventory, // Audio/Sound Effects/Misc/PlaceInInventory
    Rest, // Audio/Sound Effects/Misc/Rest
    Splash, // Audio/Sound Effects/Misc/Splash
    TunnelExplosion, // Audio/Sound Effects/Misc/TunnelExplosion
    CannotChooseActorAbilityLocation, // Audio/Sound Effects/UI/CannotChooseActorAbilityLocation
    ChangeScreen1, // Audio/Sound Effects/UI/ChangeScreen/ChangeScreen1
    ChangeScreen2, // Audio/Sound Effects/UI/ChangeScreen/ChangeScreen2
    ChangeScreen3, // Audio/Sound Effects/UI/ChangeScreen/ChangeScreen3
    ChangeSelectedAction, // Audio/Sound Effects/UI/ChangeSelectedAction
    ChooseActorAbilityLocation, // Audio/Sound Effects/UI/ChooseActorAbilityLocation
    MoveSelector, // Audio/Sound Effects/UI/MoveSelector
}
