// AUTO-GENERATED BY DialogueKeyGenerator. DO NOT EDIT.
// Regenerate with Tools > Dialogue > Regenerate DialogueKey.
// The first 1 member(s) are reserved and have no asset; after them,
// member order matches the line order of Assets/Resources/InkFilePaths.txt.

public enum DialogueKey
{
    NoDialogue, // reserved: no asset
    Csalan, // Dialogue/Camp/CampExterior/CenterCamp/Csalan
    FirstBarricadeGuards, // Dialogue/Camp/CampExterior/CenterCamp/FirstBarricadeGuards
    GuardWatchingTabor, // Dialogue/Camp/CampExterior/CenterCamp/GuardWatchingTabor
    Page, // Dialogue/Camp/CampExterior/CenterCamp/Page
    CenterCamp_Tabor, // Dialogue/Camp/CampExterior/CenterCamp/Tabor
    Temple, // Dialogue/Camp/CampExterior/CenterCamp/Temple
    Imre, // Dialogue/Camp/CampExterior/ManseCamp/Imre
    ManseFrontDoor, // Dialogue/Camp/CampExterior/ManseCamp/ManseFrontDoor
    ManseServiceEntrance, // Dialogue/Camp/CampExterior/ManseCamp/ManseServiceEntrance
    SecondBarricadeGuards, // Dialogue/Camp/CampExterior/ManseCamp/SecondBarricadeGuards
    TaborWeftHut, // Dialogue/Camp/CampExterior/ManseCamp/TaborWeftHut
    BarracksGate, // Dialogue/Camp/CampExterior/MineEntranceCamp/Barracks Gate
    GuardMuzsa, // Dialogue/Camp/CampExterior/MineEntranceCamp/GuardMuzsa
    Adela, // Dialogue/Camp/CampExterior/NECamp/Adela
    GuardTaborPunished, // Dialogue/Camp/CampExterior/NECamp/GuardTaborPunished
    GézaDuringRevolution, // Dialogue/Camp/CampExterior/NECamp/GézaDuringRevolution
    KastorDuringRevolution, // Dialogue/Camp/CampExterior/NECamp/KastorDuringRevolution
    LeafPile, // Dialogue/Camp/CampExterior/NECamp/LeafPile
    Slave5, // Dialogue/Camp/CampExterior/NECamp/Slave5
    Slave6, // Dialogue/Camp/CampExterior/NECamp/Slave6
    Slave7, // Dialogue/Camp/CampExterior/NECamp/Slave7
    Slave8, // Dialogue/Camp/CampExterior/NECamp/Slave8
    Slave9, // Dialogue/Camp/CampExterior/NECamp/Slave9
    NECamp_Tabor, // Dialogue/Camp/CampExterior/NECamp/Tabor
    UrosDuringRevolution, // Dialogue/Camp/CampExterior/NECamp/UrosDuringRevolution
    WoundedSlave, // Dialogue/Camp/CampExterior/NECamp/Wounded Slave
    WoundedSlave1, // Dialogue/Camp/CampExterior/NECamp/Wounded Slave1
    WoundedSlave2, // Dialogue/Camp/CampExterior/NECamp/Wounded Slave2
    slavesAfterKillingOverseerCampNE, // Dialogue/Camp/CampExterior/NECamp/slavesAfterKillingOverseerCampNE
    BodyPileGuard, // Dialogue/Camp/CampExterior/NWCamp/BodyPileGuard
    NWCampGuard, // Dialogue/Camp/CampExterior/NWCamp/NWCamp Guard
    TaborAfterBodyPile, // Dialogue/Camp/CampExterior/NWCamp/TaborAfterBodyPile
    TaborCunningTutorial, // Dialogue/Camp/CampExterior/NWCamp/TaborCunningTutorial
    TaborEndOfTutorial, // Dialogue/Camp/CampExterior/NWCamp/TaborEndOfTutorial
    TaborIntimidateTutorial, // Dialogue/Camp/CampExterior/NWCamp/TaborIntimidateTutorial
    TaborLeadershipTutorial, // Dialogue/Camp/CampExterior/NWCamp/TaborLeadershipTutorial
    TaborObservationTutorial, // Dialogue/Camp/CampExterior/NWCamp/TaborObservationTutorial
    SECamp_Andras, // Dialogue/Camp/CampExterior/SECamp/Andras
    SECamp_Brush, // Dialogue/Camp/CampExterior/SECamp/Brush
    SECamp_Carter, // Dialogue/Camp/CampExterior/SECamp/Carter
    SECamp_ChiefTabor, // Dialogue/Camp/CampExterior/SECamp/Chief Tabor
    CrowdSlave1, // Dialogue/Camp/CampExterior/SECamp/CrowdSlave1
    CrowdSlave2, // Dialogue/Camp/CampExterior/SECamp/CrowdSlave2
    CrowdSlave3, // Dialogue/Camp/CampExterior/SECamp/CrowdSlave3
    DirectorStatue, // Dialogue/Camp/CampExterior/SECamp/DirectorStatue
    SECamp_Ervin, // Dialogue/Camp/CampExterior/SECamp/Ervin
    GuardPunishmentStartConvo, // Dialogue/Camp/CampExterior/SECamp/GuardPunishmentStartConvo
    SECamp_Géza, // Dialogue/Camp/CampExterior/SECamp/Géza
    SECamp_Janos, // Dialogue/Camp/CampExterior/SECamp/Janos
    Kastor, // Dialogue/Camp/CampExterior/SECamp/Kastor
    Marcos, // Dialogue/Camp/CampExterior/SECamp/Marcos
    SECamp_Nandor, // Dialogue/Camp/CampExterior/SECamp/Nandor
    Pazman, // Dialogue/Camp/CampExterior/SECamp/Pazman
    Reka, // Dialogue/Camp/CampExterior/SECamp/Reka
    StatueGuard, // Dialogue/Camp/CampExterior/SECamp/StatueGuard
    TaborAfterClayFight, // Dialogue/Camp/CampExterior/SECamp/TaborAfterClayFight
    Balint, // Dialogue/Camp/CampInterior/1SlaveShack/Balint
    Seb, // Dialogue/Camp/CampInterior/1SlaveShack/Seb
    _2SlaveShack_Géza, // Dialogue/Camp/CampInterior/2SlaveShack/Géza
    IntroDialogue, // Dialogue/Camp/CampInterior/2SlaveShack/IntroDialogue
    Old_IntroDialogue, // Dialogue/Camp/CampInterior/2SlaveShack/Old_IntroDialogue
    _3SlaveShack_Andras, // Dialogue/Camp/CampInterior/3SlaveShack/Andras
    _3SlaveShack_Janos, // Dialogue/Camp/CampInterior/3SlaveShack/Janos
    JanosAfterKillingAndras, // Dialogue/Camp/CampInterior/3SlaveShack/JanosAfterKillingAndras
    Dibber, // Dialogue/Camp/CampInterior/4SlaveShack/Dibber
    KastorPlan, // Dialogue/Camp/CampInterior/4SlaveShack/KastorPlan
    KastorSkillTutorial, // Dialogue/Camp/CampInterior/4SlaveShack/KastorSkillTutorial
    _5SlaveShack_Ervin, // Dialogue/Camp/CampInterior/5SlaveShack/Ervin
    Slate, // Dialogue/Camp/CampInterior/6SlaveShack/Slate
    Thatch, // Dialogue/Camp/CampInterior/6SlaveShack/Thatch
    Vazul, // Dialogue/Camp/CampInterior/6SlaveShack/Vazul
    Dezso, // Dialogue/Camp/CampInterior/7SlaveShack/Dezso
    Loam, // Dialogue/Camp/CampInterior/7SlaveShack/Loam
    WeftAfterHostages, // Dialogue/Camp/CampInterior/7SlaveShack/WeftAfterHostages
    Weft, // Dialogue/Camp/CampInterior/8SlaveShack/Weft
    AfterTakacsFight, // Dialogue/Camp/CampInterior/Body Pile/AfterTakacsFight
    ThiefBody, // Dialogue/Camp/CampInterior/Body Pile/ThiefBody
    BarracksGuard, // Dialogue/Camp/CampInterior/GuardHouseSW/Barracks Guard
    GuardLászló, // Dialogue/Camp/CampInterior/GuardShack/Guard László
    Kende, // Dialogue/Camp/CampInterior/Mess Hall/Kende
    Beam, // Dialogue/Camp/CampInterior/Stables/Beam
    Horse, // Dialogue/Camp/CampInterior/Stables/Horse
    BarrelsWithNugget, // Dialogue/Camp/CampInterior/Stockhouse/BarrelsWithNugget
    Emese, // Dialogue/Camp/CampInterior/Stockhouse/Emese
    Uros, // Dialogue/Camp/CampInterior/Stockhouse/Uros
    PriestRikard, // Dialogue/Camp/CampInterior/Temple/PriestRikard
    WallPatch, // Dialogue/Camp/WallPatch
    AncientPortcullis, // Dialogue/Interactables/Gates/Ancient Portcullis
    AwkwardRubble, // Dialogue/Interactables/Gates/Awkward Rubble
    FallenBeam, // Dialogue/Interactables/Gates/FallenBeam
    GateWithKey, // Dialogue/Interactables/Gates/Gate With Key
    HeavyBarrels, // Dialogue/Interactables/Gates/Heavy Barrels
    LiftableGate, // Dialogue/Interactables/Gates/Liftable Gate
    LiftableRubble, // Dialogue/Interactables/Gates/LiftableRubble
    UnstablePillar, // Dialogue/Interactables/Gates/Unstable Pillar
    Ladder, // Dialogue/Interactables/Ladder
    SuspiciousWall, // Dialogue/Interactables/Suspicious Wall
    VaultableObject, // Dialogue/Interactables/VaultableObject
    VaultableOrDestroyableObject, // Dialogue/Interactables/VaultableOrDestroyableObject
    BeamAndCsalan, // Dialogue/Manse/Manse-1F/BeamAndCsalan
    LoyalImre, // Dialogue/Manse/Manse-1F/LoyalImre
    Pan, // Dialogue/Manse/Manse-1F/Pan
    kendeUponEnteringKitchens, // Dialogue/Manse/Manse-1F/kendeUponEnteringKitchens
    CaptainAdéla, // Dialogue/Manse/Manse-2F/Captain Adéla
    Manse2F_ChiefTabor, // Dialogue/Manse/Manse-2F/Chief Tabor
    Director, // Dialogue/Manse/Manse-2F/Director
    DirectorDefeatedConvo, // Dialogue/Manse/Manse-2F/DirectorDefeatedConvo
    DirectorPreRevolt, // Dialogue/Manse/Manse-2F/DirectorPreRevolt
    OfficeDoor, // Dialogue/Manse/Manse-2F/Office Door
    OfficeSecretDoor, // Dialogue/Manse/Manse-2F/OfficeSecretDoor
    PagePreRevolt, // Dialogue/Manse/Manse-2F/PagePreRevolt
    Pit_Brush, // Dialogue/Manse/Pit/Brush
    PitGate, // Dialogue/Manse/Pit/Pit Gate
    ControlPanel, // Dialogue/Mine/MineLvl_2/Control Panel
    MineArmoryGate, // Dialogue/Mine/MineLvl_2/Mine Armory Gate
    AfterKillingGuardsMineLvl3, // Dialogue/Mine/MineLvl_3/AfterKillingGuardsMineLvl3
    MineLvl_3_Carter, // Dialogue/Mine/MineLvl_3/Carter
    GuardLiftableGate, // Dialogue/Mine/MineLvl_3/Guard Liftable Gate
    GuardMarcos, // Dialogue/Mine/MineLvl_3/GuardMarcos
    GuardPazman, // Dialogue/Mine/MineLvl_3/GuardPazman
    GuardReka, // Dialogue/Mine/MineLvl_3/GuardReka
    GuardVirag, // Dialogue/Mine/MineLvl_3/GuardVirag
    GuardsCrate, // Dialogue/Mine/MineLvl_3/GuardsCrate
    MinersCrate, // Dialogue/Mine/MineLvl_3/MinersCrate
    MineLvl_3_Nandor, // Dialogue/Mine/MineLvl_3/Nandor
    Rubble, // Dialogue/Mine/MineLvl_3/Rubble
    GenericDialogue, // Dialogue/Misc/GenericDialogue
    DefaultPartyMemberDialogue, // Dialogue/PartyMembers/DefaultPartyMemberDialogue
}
