// AUTO-GENERATED BY SpritePathGenerator. DO NOT EDIT.
// Regenerate with Tools > Sprites > Regenerate SpritePath.
// The first 1 member(s) are reserved and have no asset; after them,
// member order matches the line order of Assets/Resources/SpriteLayerFilePaths.txt.

public enum SpritePath
{
    NoSprite, // reserved: no asset
    Body_LovashiArmor_OOC_Idle_Back, // Sprites/SpriteLayers/Body/Lovashi Armor/OOC_Idle_Back
    Body_LovashiArmor_OOC_Idle_Front, // Sprites/SpriteLayers/Body/Lovashi Armor/OOC_Idle_Front
    Body_LovashiArmor_Run_Back, // Sprites/SpriteLayers/Body/Lovashi Armor/Run_Back
    Body_LovashiArmor_Run_Front, // Sprites/SpriteLayers/Body/Lovashi Armor/Run_Front
    Face_Short_Goatee_OOC_Idle_Front, // Sprites/SpriteLayers/Face/Short_Goatee/OOC_Idle_Front
    Hair_Short_1, // Sprites/SpriteLayers/Hair/Short_1
    Weapon_SpearSimple_Idle_Front, // Sprites/SpriteLayers/Weapon/Spear (Simple)/Idle_Front
}
