// AUTO-GENERATED BY SpritePathGenerator. DO NOT EDIT.
// Regenerate with Tools > Sprites > Regenerate SpritePath.
// The first 1 member(s) are reserved and have no asset; after them,
// member order matches the line order of Assets/Resources/SpriteLayerFilePaths.txt.

public enum SpritePath
{
    NoSprite, // reserved: no asset
    Body_LovashiArmor_NoWeapon_OOC_Idle_Back, // Sprites/SpriteLayers/Body/LovashiArmor/NoWeapon/OOC_Idle_Back
    Body_LovashiArmor_NoWeapon_OOC_Idle_Front, // Sprites/SpriteLayers/Body/LovashiArmor/NoWeapon/OOC_Idle_Front
    Body_LovashiArmor_NoWeapon_Run_Back_Left, // Sprites/SpriteLayers/Body/LovashiArmor/NoWeapon/Run_Back_Left
    Body_LovashiArmor_NoWeapon_Run_Back_Right, // Sprites/SpriteLayers/Body/LovashiArmor/NoWeapon/Run_Back_Right
    Body_LovashiArmor_NoWeapon_Run_Front_Left, // Sprites/SpriteLayers/Body/LovashiArmor/NoWeapon/Run_Front_Left
    Body_LovashiArmor_NoWeapon_Run_Front_Right, // Sprites/SpriteLayers/Body/LovashiArmor/NoWeapon/Run_Front_Right
    Face_Short_Goatee_OOC_Idle_Front, // Sprites/SpriteLayers/Face/Short_Goatee/OOC_Idle_Front
    Hair_Short_Ruffled_OOC_Idle_Front, // Sprites/SpriteLayers/Hair/Short_Ruffled/OOC_Idle_Front
    Weapon_SpearSimple_Idle_Front, // Sprites/SpriteLayers/Weapon/SpearSimple/Idle_Front
}
